# -*- coding: utf-8 -*-
"""cproj105

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y6DhvtgzIhSXsOLeWaY5WTO__oqOdxZf
"""

import random
import plotly.express as px
import plotly.figure_factory as ff

diceResult =[]
count = []
for i in range(0, 100):
  count.append(i)
  dice1 = random.randint(1,6)
  dice2 = random.randint(1,6)
  diceResult.append(dice1+dice2)

fig = ff.create_distplot([diceResult], ["Result"])
fig.show()

from google.colab import files
data_to_load = files.upload()

import csv 
import plotly.figure_factory as ff
import pandas as pd



df = pd.read_csv("phonesdata.csv")
fig = ff.create_distplot([df["Avg Rating"].tolist()], ["Rating"])
fig.show()